import Head from "next/head";
import Image from "next/image";

const about = () => {
  const done = [
    "i was able to do a lot of cool thins",
    "test",
    "more",
    "more",
    "things",
    "test",
    "more",
    "more",
  ];
  const wantToDo = ["things", "test", "more", "more"];

  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute w-full min-h-screen bg-background">
        <div className="flex flex-col mx-auto md:mx-24">
          <h1 className="text-center md:text-left bg-clip-text text-transparent bg-gradient-to-r from-navyblue via-blue-500 to-skyblue animate-gradient-xy font-black text-7xl my-10">
            About
          </h1>
          <div className="flex flex-col md:flex-row">
            <div className="flex-shrink-0 mx-auto">
              <Image src="/profilepic.png" width="256" height="256"></Image>
            </div>
            <div className="text-center md:text-left mx-5 text-white text-lg leading-8">
              <p >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Vestibulum sagittis urna id ipsum pharetra ultricies. Donec
                bibendum ante id urna luctus, ut faucibus mauris auctor. Phasellus
                tempor ligula quis ligula tempus tincidunt semper ut leo. Nunc
                tincidunt convallis tempor. Pellentesque vestibulum tellus sit
                amet tortor hendrerit viverra.{" "}
              </p>
              <h2 className="text-2xl mt-10 font-semibold">Find me here 😉</h2>
              <div className="flex flex-row mt-4">
                <div className="mx-2 px-2 pt-1 rounded-xl duration-500 hover:bg-gray-50">
                  <Image src="/socials/github.png" height="64" width="64"/>
                </div>
                <div className="mx-2 px-2 pt-1 rounded-xl duration-500 hover:bg-gray-50">
                  <Image src="/socials/instagram.png" height="64" width="64"/>
                </div>
                <div className="mx-2 px-2 pt-1 rounded-xl duration-500 hover:bg-gray-50">
                  <Image src="/socials/medium.png" height="64" width="64"/>
                </div>
                <div className="mx-2 px-2 pt-1 rounded-xl duration-500 hover:bg-gray-50">
                  <Image src="/socials/twitter.png" height="64" width="64"/>
                </div>

              </div>
            </div>

            
          </div>
          <div className="flex flex-col md:flex-row mx-8 text-white text-lg leading-8 mt-11 md:space-x-24">
            <div>
              <h2 className="text-3xl font-medium">Some Things I've Done ✅</h2>
              <ul className="list-disc list-inside">
                <li>HELLO</li>
                <li>HELLO</li>
                <li>HELLO</li>
                <li>HELLO</li>
              </ul>
            </div>
            <div>
              <h2 className="text-3xl font-medium">Some Things I Want To Do 🧩</h2>
              <ul className="list-disc list-inside">
                <li>HELLO</li>
                <li>HELLO</li>
                <li>HELLO</li>
                <li>HELLO</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default about;
