import Head from "next/head";
import Image from 'next/image'

const about = () => {
    
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute w-full h-full bg-background overflow-hidden">
          <div className="flex flex-col">
              <h1>About</h1>
              <div className="flex flex-row">
                  <Image src="/profilepic.png" width="64" height="64"></Image>
              </div>
          </div>
      </div>
    </div>
  );
};

export default about;
