import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div
        className="flex items-center justify-center h-64">
        <h1 className="bg-clip-text text-transparent bg-gradient-to-r 
from-blue-400 
to-orange-500 
via-purple-500
animate-gradient-x text-8xl font-extrabold">
          Animated Gradient Using Tailwind CSS
        </h1>
      </div> */}
    </div>
  );
}
