import "../styles/portfolio.module.css";
import Project from "../components/Project";
import Head from "next/head";

import timelineElements from "../lib/timelineElements";

import projects from "../lib/projectsLib";

import {
  VerticalTimeline,
  VerticalTimelineElement,
} from "react-vertical-timeline-component";

import "react-vertical-timeline-component/style.min.css";

const portfolio = () => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute w-full min-h-screen bg-background">
        <h1 className="py-24 text-center mx-auto font-black text-6xl md:text-8xl bg-clip-text text-transparent bg-gradient-to-r from-navyblue via-blue-500 to-skyblue animate-gradient-xy">
          Portfolio
        </h1>
        <a href="https://drive.google.com/file/d/1d3gJfaOPk6YVslpFA_pu8VB2Uc8S0kVK/view?usp=sharing">
          <h2 className="bg-blue-700 duration-500 hover:bg-blue-800 hover:shadow-xl text-white font-bold py-4 px-4 rounded mx-auto w-56 text-center mb-4">            
              Click me for my resume!
          </h2>
        </a>

        <VerticalTimeline animate={false}>
          {timelineElements.map((element) => {
            return (
              <VerticalTimelineElement
                key={element.key}
                date={element.date}
                contentArrowStyle={{ borderRight: "7px solid  rgb(37,41,53)" }}
                contentStyle={{
                  background: "linear-gradient(to right, #1687F3 , #2a4bde)",
                  color: "#fff",
                }}
                dateClassName="date"
                iconStyle={{
                  background: "linear-gradient(to right, #1687F3 , #2a4bde)",
                }}
              >
                <h3 className="vertical-timeline-element-title font-extrabold">
                  {element.title}
                </h3>
                <p id="description" className="font-light">
                  {element.description}
                </p>
              </VerticalTimelineElement>
            );
          })}
        </VerticalTimeline>

        <h1 className="py-24 text-center mx-auto font-black text-6xl md:text-8xl bg-clip-text text-transparent bg-gradient-to-r from-navyblue via-blue-500 to-skyblue animate-gradient-xy">
          Projects
        </h1>
        <div>
          {projects.map((project) => {
            return (
              <div className="w-9/12 mx-auto">
                <Project
                  tags={project.tags}
                  name={project.title}
                  description={project.description}
                />
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

export default portfolio;
